//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThothCbz.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThothCbz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap adjusts_titles {
            get {
                object obj = ResourceManager.GetObject("adjusts_titles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap analysing_titles {
            get {
                object obj = ResourceManager.GetObject("analysing_titles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap analytics_titles {
            get {
                object obj = ResourceManager.GetObject("analytics_titles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnAdjustmentsActive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnAdjustmentsActive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnAdjustmentsHover512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnAdjustmentsHover512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnAdjustmentsInactive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnAdjustmentsInactive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnAdjustmentsPressed512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnAdjustmentsPressed512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnCancelHover512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnCancelHover512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnCancelInactive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnCancelInactive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnCancelPressed512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnCancelPressed512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnCbzActive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnCbzActive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnCbzHover512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnCbzHover512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnCbzInactive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnCbzInactive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnCbzPressed512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnCbzPressed512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnFileDisable512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnFileDisable512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnFileEnable512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnFileEnable512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnFolderDisabled512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnFolderDisabled512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnFolderHover512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnFolderHover512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnFolderInactive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnFolderInactive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnFolderPressed512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnFolderPressed512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnHelpHover512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnHelpHover512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnHelpInactive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnHelpInactive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnHelpPressed512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnHelpPressed512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnPlayHover512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnPlayHover512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnPlayInactive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnPlayInactive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnPlayPressed512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnPlayPressed512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnRefreshHover512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnRefreshHover512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnRefreshInactive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnRefreshInactive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnRefreshPressed512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnRefreshPressed512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnRenameActive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnRenameActive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnRenameHover512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnRenameHover512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnRenameInactive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnRenameInactive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnRenamePressed512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnRenamePressed512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnSeriesDisable512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnSeriesDisable512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnSeriesEnable512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnSeriesEnable512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnSplitActive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnSplitActive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnSplitHover512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnSplitHover512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnSplitInactive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnSplitInactive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnSplitPressed512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnSplitPressed512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnSplitStatisticsDisable {
            get {
                object obj = ResourceManager.GetObject("BtnSplitStatisticsDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnSplitStatisticsEnable {
            get {
                object obj = ResourceManager.GetObject("BtnSplitStatisticsEnable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnTransformationDisable512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnTransformationDisable512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnTransformationEnable512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnTransformationEnable512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnUnifyActive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnUnifyActive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnUnifyHover512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnUnifyHover512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnUnifyInactive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnUnifyInactive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnUnifyPressed512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnUnifyPressed512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnUnifyStatisticsDisable {
            get {
                object obj = ResourceManager.GetObject("BtnUnifyStatisticsDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnUnifyStatisticsEnable {
            get {
                object obj = ResourceManager.GetObject("BtnUnifyStatisticsEnable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnUnknownStatisticsDisable {
            get {
                object obj = ResourceManager.GetObject("BtnUnknownStatisticsDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnUnknownStatisticsEnable {
            get {
                object obj = ResourceManager.GetObject("BtnUnknownStatisticsEnable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnVolumesDisable512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnVolumesDisable512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnVolumesEnable512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnVolumesEnable512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnWarningsHover512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnWarningsHover512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnWarningsInactive512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnWarningsInactive512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtnWarningsPressed512x512 {
            get {
                object obj = ResourceManager.GetObject("BtnWarningsPressed512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom icon per volume file.
        /// </summary>
        internal static string CbxAddIconText {
            get {
                return ResourceManager.GetString("CbxAddIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add blank space between unified pages if the pages have diferente widths..
        /// </summary>
        internal static string CbxBlankSpaceText {
            get {
                return ResourceManager.GetString("CbxBlankSpaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable image beautifier (edit {0}).
        /// </summary>
        internal static string CbxEnableBrightnessContrastText {
            get {
                return ResourceManager.GetString("CbxEnableBrightnessContrastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscale all images for the minimal height of (in pixels):.
        /// </summary>
        internal static string CbxUpscaleImagesText {
            get {
                return ResourceManager.GetString("CbxUpscaleImagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected directory is part of the final file structure!.
        /// </summary>
        internal static string CbxUseSelectedDirectoryText {
            get {
                return ResourceManager.GetString("CbxUseSelectedDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chapter.
        /// </summary>
        internal static string ChapterNameText {
            get {
                return ResourceManager.GetString("ChapterNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AppConfiguration.json file is corrupted..
        /// </summary>
        internal static string CorruptedAppConfigurationFileText {
            get {
                return ResourceManager.GetString("CorruptedAppConfigurationFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap execution_logs_titles {
            get {
                object obj = ResourceManager.GetObject("execution_logs_titles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANALYSING.....
        /// </summary>
        internal static string FormAnalysisText {
            get {
                return ResourceManager.GetString("FormAnalysisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THOTH CBZ GENERATOR.
        /// </summary>
        internal static string FormThotCbzText {
            get {
                return ResourceManager.GetString("FormThotCbzText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        internal static string FormWarningsText {
            get {
                return ResourceManager.GetString("FormWarningsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait! We are analysing a total of {0} files..
        /// </summary>
        internal static string LblAnalysingMultiplesDescriptionText {
            get {
                return ResourceManager.GetString("LblAnalysingMultiplesDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait! We are analysing a total of {0} file..
        /// </summary>
        internal static string LblAnalysingOneDescriptionText {
            get {
                return ResourceManager.GetString("LblAnalysingOneDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to cancel the execution has been queued....
        /// </summary>
        internal static string LblCancelRequestCommandText {
            get {
                return ResourceManager.GetString("LblCancelRequestCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _COLOR_\tab \tab \u9632  _STATUS_ _FONT_ {\b {\field{\*\fldinst HYPERLINK &quot;&quot;_URI_&quot;&quot;}{\fldrslt _NAME_}}}\f0.
        /// </summary>
        internal static string LblExecutionLogChaptersText {
            get {
                return ResourceManager.GetString("LblExecutionLogChaptersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _COLOR__STATUS_ _FONT_ {\b {\field{\*\fldinst HYPERLINK &quot;&quot;_URI_&quot;&quot;}{\fldrslt _NAME_}}}\f0.
        /// </summary>
        internal static string LblExecutionLogSeriesText {
            get {
                return ResourceManager.GetString("LblExecutionLogSeriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  ANALYZED ].
        /// </summary>
        internal static string LblExecutionLogStatusAnalyzedText {
            get {
                return ResourceManager.GetString("LblExecutionLogStatusAnalyzedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [      DONE      ].
        /// </summary>
        internal static string LblExecutionLogStatusDoneText {
            get {
                return ResourceManager.GetString("LblExecutionLogStatusDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [      ERROR     ].
        /// </summary>
        internal static string LblExecutionLogStatusErrorText {
            get {
                return ResourceManager.GetString("LblExecutionLogStatusErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [    QUEUED    ].
        /// </summary>
        internal static string LblExecutionLogStatusQueueText {
            get {
                return ResourceManager.GetString("LblExecutionLogStatusQueueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [   RUNNING  ].
        /// </summary>
        internal static string LblExecutionLogStatusRunningText {
            get {
                return ResourceManager.GetString("LblExecutionLogStatusRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ ATTENTION ].
        /// </summary>
        internal static string LblExecutionLogStatusWarningText {
            get {
                return ResourceManager.GetString("LblExecutionLogStatusWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _COLOR_\tab \bullet  _STATUS_ _FONT_ {\b {\field{\*\fldinst HYPERLINK &quot;&quot;_URI_&quot;&quot;}{\fldrslt _NAME_}}}\f0.
        /// </summary>
        internal static string LblExecutionLogVolumesText {
            get {
                return ResourceManager.GetString("LblExecutionLogVolumesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEFT-TO-RIGHT.
        /// </summary>
        internal static string LblPagesReadOrderLeftRightText {
            get {
                return ResourceManager.GetString("LblPagesReadOrderLeftRightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIGHT-TO-LEFT.
        /// </summary>
        internal static string LblPagesReadOrderRightLeftText {
            get {
                return ResourceManager.GetString("LblPagesReadOrderRightLeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order of reading for all the series found are:.
        /// </summary>
        internal static string LblReadingOrderText {
            get {
                return ResourceManager.GetString("LblReadingOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages that needs to be splitted are located in the following directory:.
        /// </summary>
        internal static string LblSplitableDirectoryText {
            get {
                return ResourceManager.GetString("LblSplitableDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages that need to be unified are located in the following directory:.
        /// </summary>
        internal static string LblUnifyableDirectoryText {
            get {
                return ResourceManager.GetString("LblUnifyableDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string LblVersionText {
            get {
                return ResourceManager.GetString("LblVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the files (setting the resolution, converting to jpg and upscale)..
        /// </summary>
        internal static string PbxBtnAdjustFilesTooltipText {
            get {
                return ResourceManager.GetString("PbxBtnAdjustFilesTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel current generation..
        /// </summary>
        internal static string PbxBtnCancelTooltipText {
            get {
                return ResourceManager.GetString("PbxBtnCancelTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the base directory for execution..
        /// </summary>
        internal static string PbxBtnFolderTooltipText {
            get {
                return ResourceManager.GetString("PbxBtnFolderTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate the CBZ files (grouping and renaming files, besides the file generation)..
        /// </summary>
        internal static string PbxBtnGenerateCbzTooltipText {
            get {
                return ResourceManager.GetString("PbxBtnGenerateCbzTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Information and tips..
        /// </summary>
        internal static string PbxBtnHelpTooltipText {
            get {
                return ResourceManager.GetString("PbxBtnHelpTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute!.
        /// </summary>
        internal static string PbxBtnPlayTooltipText {
            get {
                return ResourceManager.GetString("PbxBtnPlayTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the analysis..
        /// </summary>
        internal static string PbxBtnRefreshTooltipText {
            get {
                return ResourceManager.GetString("PbxBtnRefreshTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate the pages into two..
        /// </summary>
        internal static string PbxBtnSplitPagesTooltipText {
            get {
                return ResourceManager.GetString("PbxBtnSplitPagesTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unify double pages..
        /// </summary>
        internal static string PbxBtnUnifyPagesTooltipText {
            get {
                return ResourceManager.GetString("PbxBtnUnifyPagesTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues preventing the adjusts and/or the generation..
        /// </summary>
        internal static string PbxBtnWarningTooltipText {
            get {
                return ResourceManager.GetString("PbxBtnWarningTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files found to be converted..
        /// </summary>
        internal static string PbxConversionStatisticsTooltipText {
            get {
                return ResourceManager.GetString("PbxConversionStatisticsTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files found to be processed..
        /// </summary>
        internal static string PbxFilesStatisticsTooltipText {
            get {
                return ResourceManager.GetString("PbxFilesStatisticsTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series found to be processed..
        /// </summary>
        internal static string PbxSeriesStatisticsTooltipText {
            get {
                return ResourceManager.GetString("PbxSeriesStatisticsTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files found to be splitted..
        /// </summary>
        internal static string PbxSplitStatisticsTooltipText {
            get {
                return ResourceManager.GetString("PbxSplitStatisticsTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files found to be unified..
        /// </summary>
        internal static string PbxUnifyStatisticsTooltipText {
            get {
                return ResourceManager.GetString("PbxUnifyStatisticsTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files found that have an unknwon extension..
        /// </summary>
        internal static string PbxUnknwonStatisticsTooltipText {
            get {
                return ResourceManager.GetString("PbxUnknwonStatisticsTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumes found to be processed..
        /// </summary>
        internal static string PbxVolumesStatisticsTooltipText {
            get {
                return ResourceManager.GetString("PbxVolumesStatisticsTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The executions was aborted, some unkwon issue caused that. If you want more information, verify the log &quot;{0}&quot;.
        /// </summary>
        internal static string ProcessWithErrorTxt {
            get {
                return ResourceManager.GetString("ProcessWithErrorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustments cannot be made because there are files that are not automatically adjustable by the tool..
        /// </summary>
        internal static string RtbWarningsForAdjustments001Text {
            get {
                return ResourceManager.GetString("RtbWarningsForAdjustments001Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustable extensions are &quot;.jpg&quot;, &quot;.jpeg&quot;, &quot;.img&quot;, &quot;.gif&quot;, &quot;.png&quot;, &quot;.webp&quot;..
        /// </summary>
        internal static string RtbWarningsForAdjustments002Text {
            get {
                return ResourceManager.GetString("RtbWarningsForAdjustments002Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can check which Series/Volumes/Chapters have files with unwell extensions by searching the list displayed in the &quot;Execution Logs&quot; area. These items have a tag [ERROR] before the name and in a different color..
        /// </summary>
        internal static string RtbWarningsForAdjustments003Text {
            get {
                return ResourceManager.GetString("RtbWarningsForAdjustments003Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot generate CBZ files because there are files in formats other than the expected format (.jpg)..
        /// </summary>
        internal static string RtbWarningsForCbz001Text {
            get {
                return ResourceManager.GetString("RtbWarningsForCbz001Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be able to generate CBZ files, please enable the button to make adjustments to the files. .
        /// </summary>
        internal static string RtbWarningsForCbz002Text {
            get {
                return ResourceManager.GetString("RtbWarningsForCbz002Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can check which Series/Volumes/Chapters have files that need to be adjusted by searching the list displayed in the &quot;Execution Logs&quot; area. These items have a tag [ ATTENTION ] before the name and in a different color..
        /// </summary>
        internal static string RtbWarningsForCbz003Text {
            get {
                return ResourceManager.GetString("RtbWarningsForCbz003Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot split files because there are files in formats other than the expected one (.jpg)..
        /// </summary>
        internal static string RtbWarningsForSplit001Text {
            get {
                return ResourceManager.GetString("RtbWarningsForSplit001Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be able to generate splited files, please enable the button to make adjustments to the files. .
        /// </summary>
        internal static string RtbWarningsForSplit002Text {
            get {
                return ResourceManager.GetString("RtbWarningsForSplit002Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot unify files because there are files in formats other than the expected one (.jpg)..
        /// </summary>
        internal static string RtbWarningsForUnify001Text {
            get {
                return ResourceManager.GetString("RtbWarningsForUnify001Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be able to generate unified files, please enable the button to make adjustments to the files. .
        /// </summary>
        internal static string RtbWarningsForUnify002Text {
            get {
                return ResourceManager.GetString("RtbWarningsForUnify002Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot unify files because the files amount isn&apos;t even..
        /// </summary>
        internal static string RtbWarningsForUnify003Text {
            get {
                return ResourceManager.GetString("RtbWarningsForUnify003Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be able to generate unified files, please validate and keep only even amount of files in the unifyable folders. .
        /// </summary>
        internal static string RtbWarningsForUnify004Text {
            get {
                return ResourceManager.GetString("RtbWarningsForUnify004Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can check which Series/Volumes/Chapters have even files by searching the list displayed in the &quot;Execution Logs&quot; area. These items have a tag [ERROR] before the name and in a different color..
        /// </summary>
        internal static string RtbWarningsForUnify005Text {
            get {
                return ResourceManager.GetString("RtbWarningsForUnify005Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the alerts below for the necessary actions to proceed with the execution of the adjustments and/or the generation of CBZ files..
        /// </summary>
        internal static string RtbWarningsHeaderMultiplesText {
            get {
                return ResourceManager.GetString("RtbWarningsHeaderMultiplesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check in the alert below the action required to proceed with the execution of the settings and/or the generation of CBZ files..
        /// </summary>
        internal static string RtbWarningsHeaderOneText {
            get {
                return ResourceManager.GetString("RtbWarningsHeaderOneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap series_titles {
            get {
                object obj = ResourceManager.GetObject("series_titles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series.
        /// </summary>
        internal static string SeriesNameText {
            get {
                return ResourceManager.GetString("SeriesNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_left_titles {
            get {
                object obj = ResourceManager.GetObject("settings_left_titles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_titles {
            get {
                object obj = ResourceManager.GetObject("settings_titles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap splitter {
            get {
                object obj = ResourceManager.GetObject("splitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon thoth_cbz {
            get {
                object obj = ResourceManager.GetObject("thoth_cbz", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thothBckColor {
            get {
                object obj = ResourceManager.GetObject("thothBckColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThothCbz1 {
            get {
                object obj = ResourceManager.GetObject("ThothCbz1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TreeViewStatusDone {
            get {
                object obj = ResourceManager.GetObject("TreeViewStatusDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TreeViewStatusError {
            get {
                object obj = ResourceManager.GetObject("TreeViewStatusError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TreeViewStatusQueue {
            get {
                object obj = ResourceManager.GetObject("TreeViewStatusQueue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TreeViewStatusRunning {
            get {
                object obj = ResourceManager.GetObject("TreeViewStatusRunning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TreeViewStatusWaiting {
            get {
                object obj = ResourceManager.GetObject("TreeViewStatusWaiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TreeViewStatusWarning {
            get {
                object obj = ResourceManager.GetObject("TreeViewStatusWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory with the series(s) to initialize the process..
        /// </summary>
        internal static string txtDirectoryDefaultText {
            get {
                return ResourceManager.GetString("txtDirectoryDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volume.
        /// </summary>
        internal static string VolumeNameText {
            get {
                return ResourceManager.GetString("VolumeNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap volumes_titles {
            get {
                object obj = ResourceManager.GetObject("volumes_titles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warnings_titles {
            get {
                object obj = ResourceManager.GetObject("warnings_titles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
